# POST http://localhost:5000/admin/register
# Content-Type: application/json

# {
#     "adminName": "Ngoc Y",
#     "adminEmail": "ytn@st",
#     "adminPassword": 123,
#     "adminRole": "admin"
# }

GET http://localhost:5000/admin